print("Getting to Know You 😊")
print()
userName = input("What is your name?: ")
favouriteFood = input("Your favourite food is: ")
userLocation = input("Where do you live?: ")
favouriteMusic = input("What song do you love jamming to?: ")
print()
print("You are")
print(userName)
print("and your favourite food is")
print(favouriteFood)
print("You're currently living in the beautiful city")
print(userLocation)
print("and in your free time, you love jamming to")
print(favouriteMusic)
print("You're Awesome 🤘🤘")