print("RECIPE MAKER 🧑‍🍳🧑‍🍳")
print()
food = input("Name a type of food: ")
plant = input("Name a type of plant: ")
cookingMethod = input("Name a method of cooking: ")
burnedFood = input("What word can you use to describe burnt food?: ")
item = input("Name a household item: ")
print()
print("MENU")
print(cookingMethod, food, "with", burnedFood, plant, "on a bed of", item)